#!/usr/bin/env python3
"""
Turtle.AI-coder - A web server for loading and running custom AI models
Inspired by llama.cpp server interface
"""

import argparse
import json
import time
import uuid
from http.server import HTTPServer, BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs
import html
import threading
import sys

# Global model state
class ModelState:
    def __init__(self):
        self.model_path = None
        self.model_loaded = False
        self.model_name = None
        self.model_type = "custom"
        self.context_size = 4096
        self.temperature = 0.7
        self.max_tokens = 512
        
model_state = ModelState()

def generate_response(prompt, temperature=0.7, max_tokens=512):
    """
    Simulate AI response generation.
    In a real implementation, this would load your custom model and generate text.
    """
    # This is a placeholder - replace with actual model inference
    responses = [
        "This is a simulated response from Turtle.AI-coder. In a real implementation, this would be generated by your custom AI model.",
        "I'm Turtle.AI-coder, ready to help you with coding tasks. Load your custom model to get started!",
        "Thank you for using Turtle.AI-coder. This demo shows the interface structure for your custom AI model.",
    ]
    import random
    return random.choice(responses)

class TurtleAIHandler(BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        print(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] {args[0]}")
    
    def send_cors_headers(self):
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
    
    def do_OPTIONS(self):
        self.send_response(200)
        self.send_cors_headers()
        self.end_headers()
    
    def do_GET(self):
        parsed_path = urlparse(self.path)
        path = parsed_path.path
        
        if path == '/' or path == '/index.html':
            self.serve_main_page()
        elif path == '/health':
            self.serve_health()
        elif path == '/models':
            self.serve_models_info()
        elif path == '/settings':
            self.serve_settings()
        else:
            self.send_error(404, "Not Found")
    
    def do_POST(self):
        parsed_path = urlparse(self.path)
        path = parsed_path.path
        
        content_length = int(self.headers.get('Content-Length', 0))
        post_data = self.rfile.read(content_length).decode('utf-8') if content_length > 0 else '{}'
        
        try:
            data = json.loads(post_data) if post_data else {}
        except json.JSONDecodeError:
            data = {}
        
        if path == '/completion':
            self.serve_completion(data)
        elif path == '/chat/completions':
            self.serve_chat_completion(data)
        elif path == '/load_model':
            self.serve_load_model(data)
        elif path == '/unload_model':
            self.serve_unload_model()
        else:
            self.send_error(404, "Not Found")
    
    def serve_main_page(self):
        html_content = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Turtle.AI-coder</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            color: #e0e0e0;
            min-height: 100vh;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }
        
        header {
            background: rgba(255, 255, 255, 0.05);
            backdrop-filter: blur(10px);
            border-bottom: 1px solid rgba(255, 255, 255, 0.1);
            padding: 20px 0;
            margin-bottom: 30px;
        }
        
        .header-content {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        
        .logo {
            display: flex;
            align-items: center;
            gap: 15px;
        }
        
        .logo-icon {
            width: 50px;
            height: 50px;
            background: linear-gradient(135deg, #00d9ff 0%, #00ff88 100%);
            border-radius: 12px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 24px;
            font-weight: bold;
            color: #1a1a2e;
        }
        
        h1 {
            font-size: 28px;
            font-weight: 600;
            background: linear-gradient(135deg, #00d9ff 0%, #00ff88 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }
        
        .status-bar {
            display: flex;
            gap: 20px;
            align-items: center;
        }
        
        .status-item {
            display: flex;
            align-items: center;
            gap: 8px;
            padding: 8px 16px;
            background: rgba(255, 255, 255, 0.05);
            border-radius: 8px;
            font-size: 14px;
        }
        
        .status-dot {
            width: 8px;
            height: 8px;
            border-radius: 50%;
            background: #ff4757;
        }
        
        .status-dot.active {
            background: #2ed573;
            box-shadow: 0 0 10px #2ed573;
        }
        
        .main-content {
            display: grid;
            grid-template-columns: 1fr 350px;
            gap: 20px;
        }
        
        .chat-section {
            background: rgba(255, 255, 255, 0.05);
            backdrop-filter: blur(10px);
            border-radius: 16px;
            border: 1px solid rgba(255, 255, 255, 0.1);
            overflow: hidden;
        }
        
        .chat-messages {
            height: 500px;
            overflow-y: auto;
            padding: 20px;
            display: flex;
            flex-direction: column;
            gap: 15px;
        }
        
        .message {
            max-width: 80%;
            padding: 15px 20px;
            border-radius: 12px;
            line-height: 1.6;
        }
        
        .message.user {
            align-self: flex-end;
            background: linear-gradient(135deg, #00d9ff 0%, #0099cc 100%);
            color: #1a1a2e;
        }
        
        .message.assistant {
            align-self: flex-start;
            background: rgba(255, 255, 255, 0.1);
            border: 1px solid rgba(255, 255, 255, 0.1);
        }
        
        .chat-input-section {
            border-top: 1px solid rgba(255, 255, 255, 0.1);
            padding: 20px;
        }
        
        .chat-input-container {
            display: flex;
            gap: 10px;
        }
        
        #userInput {
            flex: 1;
            padding: 15px 20px;
            background: rgba(255, 255, 255, 0.05);
            border: 1px solid rgba(255, 255, 255, 0.1);
            border-radius: 12px;
            color: #e0e0e0;
            font-size: 15px;
            resize: none;
            outline: none;
            transition: all 0.3s;
        }
        
        #userInput:focus {
            border-color: #00d9ff;
            box-shadow: 0 0 20px rgba(0, 217, 255, 0.2);
        }
        
        #sendBtn {
            padding: 15px 30px;
            background: linear-gradient(135deg, #00d9ff 0%, #00ff88 100%);
            border: none;
            border-radius: 12px;
            color: #1a1a2e;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.3s;
        }
        
        #sendBtn:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 30px rgba(0, 217, 255, 0.3);
        }
        
        #sendBtn:disabled {
            opacity: 0.5;
            cursor: not-allowed;
            transform: none;
        }
        
        .sidebar {
            display: flex;
            flex-direction: column;
            gap: 20px;
        }
        
        .panel {
            background: rgba(255, 255, 255, 0.05);
            backdrop-filter: blur(10px);
            border-radius: 16px;
            border: 1px solid rgba(255, 255, 255, 0.1);
            padding: 20px;
        }
        
        .panel h3 {
            font-size: 18px;
            margin-bottom: 15px;
            color: #00d9ff;
        }
        
        .form-group {
            margin-bottom: 15px;
        }
        
        .form-group label {
            display: block;
            margin-bottom: 8px;
            font-size: 14px;
            color: #b0b0b0;
        }
        
        .form-group input,
        .form-group select {
            width: 100%;
            padding: 10px 15px;
            background: rgba(255, 255, 255, 0.05);
            border: 1px solid rgba(255, 255, 255, 0.1);
            border-radius: 8px;
            color: #e0e0e0;
            font-size: 14px;
            outline: none;
        }
        
        .form-group input:focus,
        .form-group select:focus {
            border-color: #00d9ff;
        }
        
        .btn {
            width: 100%;
            padding: 12px 20px;
            border: none;
            border-radius: 8px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.3s;
            margin-bottom: 10px;
        }
        
        .btn-primary {
            background: linear-gradient(135deg, #00d9ff 0%, #00ff88 100%);
            color: #1a1a2e;
        }
        
        .btn-primary:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 30px rgba(0, 217, 255, 0.3);
        }
        
        .btn-secondary {
            background: rgba(255, 255, 255, 0.1);
            color: #e0e0e0;
            border: 1px solid rgba(255, 255, 255, 0.2);
        }
        
        .btn-secondary:hover {
            background: rgba(255, 255, 255, 0.15);
        }
        
        .model-info {
            background: rgba(0, 217, 255, 0.1);
            border: 1px solid rgba(0, 217, 255, 0.3);
            border-radius: 8px;
            padding: 15px;
            margin-bottom: 15px;
        }
        
        .model-info p {
            font-size: 13px;
            margin-bottom: 5px;
        }
        
        .model-info strong {
            color: #00d9ff;
        }
        
        .typing-indicator {
            display: flex;
            gap: 5px;
            padding: 15px 20px;
        }
        
        .typing-indicator span {
            width: 8px;
            height: 8px;
            background: #00d9ff;
            border-radius: 50%;
            animation: typing 1.4s infinite;
        }
        
        .typing-indicator span:nth-child(2) {
            animation-delay: 0.2s;
        }
        
        .typing-indicator span:nth-child(3) {
            animation-delay: 0.4s;
        }
        
        @keyframes typing {
            0%, 60%, 100% {
                transform: translateY(0);
                opacity: 0.4;
            }
            30% {
                transform: translateY(-10px);
                opacity: 1;
            }
        }
        
        ::-webkit-scrollbar {
            width: 8px;
        }
        
        ::-webkit-scrollbar-track {
            background: rgba(255, 255, 255, 0.05);
        }
        
        ::-webkit-scrollbar-thumb {
            background: rgba(255, 255, 255, 0.2);
            border-radius: 4px;
        }
        
        ::-webkit-scrollbar-thumb:hover {
            background: rgba(255, 255, 255, 0.3);
        }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <div class="header-content">
                <div class="logo">
                    <div class="logo-icon">🐢</div>
                    <h1>Turtle.AI-coder</h1>
                </div>
                <div class="status-bar">
                    <div class="status-item">
                        <div class="status-dot" id="modelStatus"></div>
                        <span id="modelStatusText">No model loaded</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    
    <div class="container">
        <div class="main-content">
            <div class="chat-section">
                <div class="chat-messages" id="chatMessages">
                    <div class="message assistant">
                        Welcome to Turtle.AI-coder! Load your custom AI model to get started. This interface is inspired by llama.cpp and designed for running your own trained models.
                    </div>
                </div>
                <div class="chat-input-section">
                    <div class="chat-input-container">
                        <textarea id="userInput" rows="1" placeholder="Type your message here..." onkeydown="if(event.key === 'Enter' && !event.shiftKey){event.preventDefault(); sendMessage();}"></textarea>
                        <button id="sendBtn" onclick="sendMessage()">Send</button>
                    </div>
                </div>
            </div>
            
            <div class="sidebar">
                <div class="panel">
                    <h3>🤖 Model Control</h3>
                    <div class="model-info" id="modelInfo" style="display: none;">
                        <p><strong>Model:</strong> <span id="modelNameDisplay"></span></p>
                        <p><strong>Type:</strong> <span id="modelTypeDisplay"></span></p>
                        <p><strong>Context:</strong> <span id="contextSizeDisplay"></span></p>
                    </div>
                    <div class="form-group">
                        <label for="modelPath">Model Path</label>
                        <input type="text" id="modelPath" placeholder="/path/to/your/model.gguf">
                    </div>
                    <button class="btn btn-primary" onclick="loadModel()">Load Model</button>
                    <button class="btn btn-secondary" onclick="unloadModel()">Unload Model</button>
                </div>
                
                <div class="panel">
                    <h3>⚙️ Generation Settings</h3>
                    <div class="form-group">
                        <label for="temperature">Temperature: <span id="tempValue">0.7</span></label>
                        <input type="range" id="temperature" min="0" max="2" step="0.1" value="0.7" oninput="document.getElementById('tempValue').textContent = this.value">
                    </div>
                    <div class="form-group">
                        <label for="maxTokens">Max Tokens</label>
                        <input type="number" id="maxTokens" value="512" min="1" max="4096">
                    </div>
                    <div class="form-group">
                        <label for="contextSize">Context Size</label>
                        <input type="number" id="contextSize" value="4096" min="512" max="8192">
                    </div>
                    <button class="btn btn-secondary" onclick="updateSettings()">Apply Settings</button>
                </div>
                
                <div class="panel">
                    <h3>ℹ️ Server Info</h3>
                    <div class="model-info">
                        <p><strong>Server:</strong> Turtle.AI-coder v1.0</p>
                        <p><strong>API:</strong> OpenAI-compatible</p>
                        <p><strong>Status:</strong> <span id="serverStatus">Running</span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script>
        let isModelLoaded = false;
        
        function addMessage(content, role) {
            const chatMessages = document.getElementById('chatMessages');
            const messageDiv = document.createElement('div');
            messageDiv.className = `message ${role}`;
            messageDiv.textContent = content;
            chatMessages.appendChild(messageDiv);
            chatMessages.scrollTop = chatMessages.scrollHeight;
            return messageDiv;
        }
        
        function showTypingIndicator() {
            const chatMessages = document.getElementById('chatMessages');
            const indicator = document.createElement('div');
            indicator.className = 'message assistant typing-indicator';
            indicator.id = 'typingIndicator';
            indicator.innerHTML = '<span></span><span></span><span></span>';
            chatMessages.appendChild(indicator);
            chatMessages.scrollTop = chatMessages.scrollHeight;
        }
        
        function removeTypingIndicator() {
            const indicator = document.getElementById('typingIndicator');
            if (indicator) {
                indicator.remove();
            }
        }
        
        async function sendMessage() {
            const userInput = document.getElementById('userInput');
            const sendBtn = document.getElementById('sendBtn');
            const message = userInput.value.trim();
            
            if (!message) return;
            if (!isModelLoaded) {
                alert('Please load a model first!');
                return;
            }
            
            addMessage(message, 'user');
            userInput.value = '';
            sendBtn.disabled = true;
            showTypingIndicator();
            
            try {
                const temperature = parseFloat(document.getElementById('temperature').value);
                const maxTokens = parseInt(document.getElementById('maxTokens').value);
                
                const response = await fetch('/completion', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        prompt: message,
                        temperature: temperature,
                        max_tokens: maxTokens,
                        stream: false
                    })
                });
                
                removeTypingIndicator();
                
                if (response.ok) {
                    const data = await response.json();
                    const content = data.content || data.text || data.choices?.[0]?.message?.content || 'No response generated';
                    addMessage(content, 'assistant');
                } else {
                    addMessage('Error: Failed to get response from server', 'assistant');
                }
            } catch (error) {
                removeTypingIndicator();
                addMessage(`Error: ${error.message}`, 'assistant');
            }
            
            sendBtn.disabled = false;
            userInput.focus();
        }
        
        async function loadModel() {
            const modelPath = document.getElementById('modelPath').value.trim();
            
            if (!modelPath) {
                alert('Please enter a model path');
                return;
            }
            
            try {
                const response = await fetch('/load_model', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        model: modelPath
                    })
                });
                
                const data = await response.json();
                
                if (response.ok && data.success) {
                    isModelLoaded = true;
                    document.getElementById('modelStatus').classList.add('active');
                    document.getElementById('modelStatusText').textContent = 'Model loaded';
                    document.getElementById('modelInfo').style.display = 'block';
                    document.getElementById('modelNameDisplay').textContent = data.model_name || modelPath;
                    document.getElementById('modelTypeDisplay').textContent = data.model_type || 'custom';
                    document.getElementById('contextSizeDisplay').textContent = data.context_size || '4096';
                    
                    addMessage(`Model loaded successfully: ${data.model_name || modelPath}`, 'assistant');
                } else {
                    alert(`Failed to load model: ${data.error || 'Unknown error'}`);
                }
            } catch (error) {
                alert(`Error loading model: ${error.message}`);
            }
        }
        
        async function unloadModel() {
            try {
                const response = await fetch('/unload_model', {
                    method: 'POST'
                });
                
                const data = await response.json();
                
                if (response.ok && data.success) {
                    isModelLoaded = false;
                    document.getElementById('modelStatus').classList.remove('active');
                    document.getElementById('modelStatusText').textContent = 'No model loaded';
                    document.getElementById('modelInfo').style.display = 'none';
                    
                    addMessage('Model unloaded successfully', 'assistant');
                } else {
                    alert(`Failed to unload model: ${data.error || 'Unknown error'}`);
                }
            } catch (error) {
                alert(`Error unloading model: ${error.message}`);
            }
        }
        
        async function updateSettings() {
            const temperature = parseFloat(document.getElementById('temperature').value);
            const maxTokens = parseInt(document.getElementById('maxTokens').value);
            const contextSize = parseInt(document.getElementById('contextSize').value);
            
            try {
                const response = await fetch('/settings', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        temperature: temperature,
                        max_tokens: maxTokens,
                        context_size: contextSize
                    })
                });
                
                if (response.ok) {
                    alert('Settings updated successfully!');
                } else {
                    alert('Failed to update settings');
                }
            } catch (error) {
                alert(`Error updating settings: ${error.message}`);
            }
        }
        
        // Auto-resize textarea
        const textarea = document.getElementById('userInput');
        textarea.addEventListener('input', function() {
            this.style.height = 'auto';
            this.style.height = (this.scrollHeight) + 'px';
        });
        
        // Check server health on load
        async function checkHealth() {
            try {
                const response = await fetch('/health');
                if (response.ok) {
                    const data = await response.json();
                    document.getElementById('serverStatus').textContent = `Running (${data.uptime}s)`;
                    if (data.model_loaded) {
                        isModelLoaded = true;
                        document.getElementById('modelStatus').classList.add('active');
                        document.getElementById('modelStatusText').textContent = 'Model loaded';
                        document.getElementById('modelInfo').style.display = 'block';
                        document.getElementById('modelNameDisplay').textContent = data.model_name || 'Unknown';
                    }
                }
            } catch (error) {
                console.error('Health check failed:', error);
            }
        }
        
        checkHealth();
        setInterval(checkHealth, 30000);
    </script>
</body>
</html>'''
        
        self.send_response(200)
        self.send_header('Content-Type', 'text/html; charset=utf-8')
        self.send_cors_headers()
        self.end_headers()
        self.wfile.write(html_content.encode('utf-8'))
    
    def serve_health(self):
        response_data = {
            'status': 'ok',
            'model_loaded': model_state.model_loaded,
            'model_name': model_state.model_name,
            'uptime': int(time.time() - start_time) if 'start_time' in globals() else 0
        }
        
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.send_cors_headers()
        self.end_headers()
        self.wfile.write(json.dumps(response_data).encode('utf-8'))
    
    def serve_models_info(self):
        response_data = {
            'object': 'list',
            'data': []
        }
        
        if model_state.model_loaded:
            response_data['data'].append({
                'id': model_state.model_name or 'custom-model',
                'object': 'model',
                'created': int(time.time()),
                'owned_by': 'turtle-ai',
                'model_type': model_state.model_type
            })
        
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.send_cors_headers()
        self.end_headers()
        self.wfile.write(json.dumps(response_data).encode('utf-8'))
    
    def serve_settings(self):
        if self.command == 'GET':
            response_data = {
                'temperature': model_state.temperature,
                'max_tokens': model_state.max_tokens,
                'context_size': model_state.context_size
            }
            
            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.send_cors_headers()
            self.end_headers()
            self.wfile.write(json.dumps(response_data).encode('utf-8'))
        elif self.command == 'POST':
            content_length = int(self.headers.get('Content-Length', 0))
            post_data = self.rfile.read(content_length).decode('utf-8') if content_length > 0 else '{}'
            
            try:
                data = json.loads(post_data)
                if 'temperature' in data:
                    model_state.temperature = float(data['temperature'])
                if 'max_tokens' in data:
                    model_state.max_tokens = int(data['max_tokens'])
                if 'context_size' in data:
                    model_state.context_size = int(data['context_size'])
                
                response_data = {
                    'success': True,
                    'temperature': model_state.temperature,
                    'max_tokens': model_state.max_tokens,
                    'context_size': model_state.context_size
                }
                
                self.send_response(200)
                self.send_header('Content-Type', 'application/json')
                self.send_cors_headers()
                self.end_headers()
                self.wfile.write(json.dumps(response_data).encode('utf-8'))
            except Exception as e:
                self.send_error(400, str(e))
    
    def serve_completion(self, data):
        if not model_state.model_loaded:
            response_data = {
                'error': {
                    'message': 'No model loaded',
                    'type': 'invalid_request_error'
                }
            }
            self.send_response(400)
            self.send_header('Content-Type', 'application/json')
            self.send_cors_headers()
            self.end_headers()
            self.wfile.write(json.dumps(response_data).encode('utf-8'))
            return
        
        prompt = data.get('prompt', '')
        temperature = data.get('temperature', model_state.temperature)
        max_tokens = data.get('max_tokens', model_state.max_tokens)
        stream = data.get('stream', False)
        
        if stream:
            self.stream_completion(prompt, temperature, max_tokens)
        else:
            generated_text = generate_response(prompt, temperature, max_tokens)
            
            response_data = {
                'id': f'cmpl-{uuid.uuid4()}',
                'object': 'text_completion',
                'created': int(time.time()),
                'model': model_state.model_name or 'custom-model',
                'choices': [
                    {
                        'text': generated_text,
                        'index': 0,
                        'logprobs': None,
                        'finish_reason': 'stop'
                    }
                ],
                'usage': {
                    'prompt_tokens': len(prompt.split()),
                    'completion_tokens': len(generated_text.split()),
                    'total_tokens': len(prompt.split()) + len(generated_text.split())
                }
            }
            
            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.send_cors_headers()
            self.end_headers()
            self.wfile.write(json.dumps(response_data).encode('utf-8'))
    
    def stream_completion(self, prompt, temperature, max_tokens):
        self.send_response(200)
        self.send_header('Content-Type', 'text/event-stream')
        self.send_cors_headers()
        self.end_headers()
        
        generated_text = generate_response(prompt, temperature, max_tokens)
        tokens = generated_text.split()
        
        for i, token in enumerate(tokens):
            chunk_data = {
                'id': f'cmpl-{uuid.uuid4()}',
                'object': 'text_completion',
                'created': int(time.time()),
                'model': model_state.model_name or 'custom-model',
                'choices': [
                    {
                        'text': token + ' ',
                        'index': 0,
                        'logprobs': None,
                        'finish_reason': None
                    }
                ]
            }
            
            self.wfile.write(f"data: {json.dumps(chunk_data)}\n\n".encode('utf-8'))
            self.wfile.flush()
            time.sleep(0.05)
        
        final_chunk = {
            'id': f'cmpl-{uuid.uuid4()}',
            'object': 'text_completion',
            'created': int(time.time()),
            'model': model_state.model_name or 'custom-model',
            'choices': [
                {
                    'text': '',
                    'index': 0,
                    'logprobs': None,
                    'finish_reason': 'stop'
                }
            ]
        }
        
        self.wfile.write(f"data: {json.dumps(final_chunk)}\n\n".encode('utf-8'))
        self.wfile.write(b"data: [DONE]\n\n")
        self.wfile.flush()
    
    def serve_chat_completion(self, data):
        if not model_state.model_loaded:
            response_data = {
                'error': {
                    'message': 'No model loaded',
                    'type': 'invalid_request_error'
                }
            }
            self.send_response(400)
            self.send_header('Content-Type', 'application/json')
            self.send_cors_headers()
            self.end_headers()
            self.wfile.write(json.dumps(response_data).encode('utf-8'))
            return
        
        messages = data.get('messages', [])
        temperature = data.get('temperature', model_state.temperature)
        max_tokens = data.get('max_tokens', model_state.max_tokens)
        
        # Convert chat messages to prompt
        prompt = ""
        for msg in messages:
            role = msg.get('role', 'user')
            content = msg.get('content', '')
            if role == 'user':
                prompt += f"User: {content}\n"
            elif role == 'assistant':
                prompt += f"Assistant: {content}\n"
        
        generated_text = generate_response(prompt, temperature, max_tokens)
        
        response_data = {
            'id': f'chatcmpl-{uuid.uuid4()}',
            'object': 'chat.completion',
            'created': int(time.time()),
            'model': model_state.model_name or 'custom-model',
            'choices': [
                {
                    'index': 0,
                    'message': {
                        'role': 'assistant',
                        'content': generated_text
                    },
                    'finish_reason': 'stop'
                }
            ],
            'usage': {
                'prompt_tokens': len(prompt.split()),
                'completion_tokens': len(generated_text.split()),
                'total_tokens': len(prompt.split()) + len(generated_text.split())
            }
        }
        
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.send_cors_headers()
        self.end_headers()
        self.wfile.write(json.dumps(response_data).encode('utf-8'))
    
    def serve_load_model(self, data):
        model_path = data.get('model', '')
        
        if not model_path:
            response_data = {
                'success': False,
                'error': 'No model path provided'
            }
            self.send_response(400)
            self.send_header('Content-Type', 'application/json')
            self.send_cors_headers()
            self.end_headers()
            self.wfile.write(json.dumps(response_data).encode('utf-8'))
            return
        
        # In a real implementation, you would load your custom model here
        # For now, we simulate successful loading
        model_state.model_path = model_path
        model_state.model_loaded = True
        model_state.model_name = model_path.split('/')[-1] if '/' in model_path else model_path
        model_state.model_type = "custom"
        
        print(f"[INFO] Model loaded: {model_state.model_name}")
        
        response_data = {
            'success': True,
            'model_name': model_state.model_name,
            'model_type': model_state.model_type,
            'context_size': model_state.context_size,
            'message': 'Model loaded successfully (simulation mode)'
        }
        
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.send_cors_headers()
        self.end_headers()
        self.wfile.write(json.dumps(response_data).encode('utf-8'))
    
    def serve_unload_model(self):
        if not model_state.model_loaded:
            response_data = {
                'success': False,
                'error': 'No model loaded'
            }
            self.send_response(400)
            self.send_header('Content-Type', 'application/json')
            self.send_cors_headers()
            self.end_headers()
            self.wfile.write(json.dumps(response_data).encode('utf-8'))
            return
        
        model_name = model_state.model_name
        model_state.model_path = None
        model_state.model_loaded = False
        model_state.model_name = None
        
        print(f"[INFO] Model unloaded: {model_name}")
        
        response_data = {
            'success': True,
            'message': 'Model unloaded successfully'
        }
        
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.send_cors_headers()
        self.end_headers()
        self.wfile.write(json.dumps(response_data).encode('utf-8'))


def main():
    global start_time
    start_time = time.time()
    
    parser = argparse.ArgumentParser(description='Turtle.AI-coder - Custom AI Model Server')
    parser.add_argument('--host', type=str, default='127.0.0.1', help='Host to bind to (default: 127.0.0.1)')
    parser.add_argument('--port', type=int, default=8080, help='Port to bind to (default: 8080)')
    parser.add_argument('--model', type=str, help='Path to model file to load on startup')
    parser.add_argument('--context-size', type=int, default=4096, help='Context size (default: 4096)')
    parser.add_argument('--threads', type=int, default=4, help='Number of threads (default: 4)')
    
    args = parser.parse_args()
    
    if args.model:
        model_state.model_path = args.model
        model_state.model_loaded = True
        model_state.model_name = args.model.split('/')[-1]
        print(f"[INFO] Pre-loaded model: {model_state.model_name}")
    
    model_state.context_size = args.context_size
    
    server_address = (args.host, args.port)
    httpd = HTTPServer(server_address, TurtleAIHandler)
    
    print("=" * 60)
    print("🐢 Turtle.AI-coder Server")
    print("=" * 60)
    print(f"Server running on: http://{args.host}:{args.port}")
    print(f"Model loaded: {model_state.model_loaded}")
    if model_state.model_loaded:
        print(f"Model name: {model_state.model_name}")
    print(f"Context size: {model_state.context_size}")
    print("=" * 60)
    print("API Endpoints:")
    print("  GET  /              - Web interface")
    print("  GET  /health        - Health check")
    print("  GET  /models        - List models")
    print("  GET  /settings      - Get settings")
    print("  POST /completion    - Text completion")
    print("  POST /chat/completions - Chat completion")
    print("  POST /load_model    - Load model")
    print("  POST /unload_model  - Unload model")
    print("=" * 60)
    print("Press Ctrl+C to stop the server")
    print("=" * 60)
    
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\n[INFO] Server shutting down...")
        httpd.shutdown()


if __name__ == '__main__':
    main()
